//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMDS.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class offer
    {
        public string IT_ID { get; set; }
        public string IT_NAME { get; set; }
        public string IT_BUY_NOW_PRICE { get; set; }
        public string PRICE_WITH_DELIVERY { get; set; }
        public string BUY_COUNT { get; set; }
        public string BOLD { get; set; }
        public string FEATURED { get; set; }
        public string THUMB { get; set; }
        public string SHOP_ITEM { get; set; }
        public string FREE_SHIPPING { get; set; }
        public string HIGHLIGHT { get; set; }
        public string SA { get; set; }
        public string samsung { get; set; }
        public string galaxy { get; set; }
        public string etui { get; set; }
        public string sony { get; set; }
        public string iphone { get; set; }
        public string xperia { get; set; }
        public string nokia { get; set; }
        public string lg { get; set; }
        public string usb { get; set; }
        public string bateria { get; set; }
        public string lumia { get; set; }
        public string mini { get; set; }
        public string hp { get; set; }
        public string folia { get; set; }
        public string htc { get; set; }
        public string lenovo { get; set; }
        public string dell { get; set; }
        public string obudowa { get; set; }
        public string pokrowiec { get; set; }
        public string radio { get; set; }
        public string laptop { get; set; }
        public string tablet { get; set; }
        public string s4 { get; set; }
        public string lte { get; set; }
        public string uchwyt { get; set; }
        public string lcd { get; set; }
        public string telefon { get; set; }
        public string s5 { get; set; }
        public string huawei { get; set; }
        public string pro { get; set; }
        public string kabel { get; set; }
        public string karta { get; set; }
        public string s3 { get; set; }
        public string plus { get; set; }
        public string kamera { get; set; }
        public string @case { get; set; }
        public string led { get; set; }
        public string fv { get; set; }
        public string wifi { get; set; }
        public string nowy { get; set; }
        public string apple { get; set; }
        public string odkurzacz { get; set; }
        public string klawiatura { get; set; }
        public string zasilacz { get; set; }
        public string antena { get; set; }
        public string bluetooth { get; set; }
        public string zestaw { get; set; }
        public string słuchawki { get; set; }
        public string asus { get; set; }
        public string canon { get; set; }
        public string C8gb { get; set; }
        public string C5s { get; set; }
        public string dysk { get; set; }
        public string Ładowarka { get; set; }
        public string xbox { get; set; }
        public string laptopa { get; set; }
        public string C4s { get; set; }
        public string z1 { get; set; }
        public string hd { get; set; }
        public string desire { get; set; }
        public string sd { get; set; }
        public string tv { get; set; }
        public string C4gb { get; set; }
        public string adapter { get; set; }
        public string tusz { get; set; }
        public string nowa { get; set; }
        public string pl { get; set; }
        public string note { get; set; }
        public string core { get; set; }
        public string gps { get; set; }
        public string nikon { get; set; }
        public string grand { get; set; }
        public string windows { get; set; }
        public string router { get; set; }
        public string s6 { get; set; }
        public string micro { get; set; }
        public string hdmi { get; set; }
        public string nawigacja { get; set; }
        public string philips { get; set; }
        public string mp3 { get; set; }
        public string dotyk { get; set; }
        public string prime { get; set; }
        public string monitor { get; set; }
        public string samochodowe { get; set; }
        public string C16gb { get; set; }
        public string pilot { get; set; }
        public string ssd { get; set; }
        public string tab { get; set; }
        public string stacja { get; set; }
        public string futerał { get; set; }
        public string trend { get; set; }
        public string czarny { get; set; }
        public string wzmacniacz { get; set; }
        public string kabura { get; set; }
        public string telewizor { get; set; }
        public string samochodowy { get; set; }
        public string gw { get; set; }
        public string dual { get; set; }
        public string ramka { get; set; }
        public string hartowane_ { get; set; }
    }
}
